#!/usr/bin/env bash
set -euo pipefail

DOTFILES="$(cd "$(dirname "$0")" && pwd)"

echo "Deploying from $DOTFILES ..."

# Hyprland custom config
cp "$DOTFILES/hypr/custom.conf" "$HOME/.config/hypr/conf/custom.conf"
echo "  -> hypr/conf/custom.conf"

# Hyprland plugin auto-rebuild script (run via exec-once in custom.conf)
mkdir -p "$HOME/.local/bin"
cp "$DOTFILES/hypr/hyprpm-autoupdate.sh" "$HOME/.local/bin/hyprpm-autoupdate.sh"
chmod +x "$HOME/.local/bin/hyprpm-autoupdate.sh"
echo "  -> ~/.local/bin/hyprpm-autoupdate.sh"
cp "$DOTFILES/hypr/reload-desktop.sh" "$HOME/.local/bin/reload-desktop.sh"
chmod +x "$HOME/.local/bin/reload-desktop.sh"
echo "  -> ~/.local/bin/reload-desktop.sh"

# Current-project dev workflow.
mkdir -p "$HOME/.config/dev" "$HOME/.local/bin"
cp "$DOTFILES/dev/projects.json" "$HOME/.config/dev/projects.json"
echo "  -> dev/projects.json"
if [ ! -s "$HOME/.config/dev/current-project" ]; then
    python3 - "$HOME/.config/dev/projects.json" "$HOME/.config/dev/current-project" <<'PY'
import json
import sys
from pathlib import Path

projects_path = Path(sys.argv[1])
current_path = Path(sys.argv[2])
projects = json.loads(projects_path.read_text())
if projects:
    current_path.write_text(str(projects[0]["path"]) + "\n")
PY
    echo "  -> dev/current-project"
fi
cp "$DOTFILES/dev/scripts/dev-project" "$HOME/.local/bin/dev-project"
chmod +x "$HOME/.local/bin/dev-project"
echo "  -> ~/.local/bin/dev-project"
"$HOME/.local/bin/dev-project" scan --quiet
echo "  -> dev/projects.json scan"
cp "$DOTFILES/dev/scripts/project-hub-watch" "$HOME/.local/bin/project-hub-watch"
chmod +x "$HOME/.local/bin/project-hub-watch"
echo "  -> ~/.local/bin/project-hub-watch"

# Dotfiles sync helper + pacman hook.
chmod +x "$DOTFILES/scripts/dotfiles-sync.sh" \
    "$DOTFILES/scripts/dotfiles-pacman-hook.sh" \
    "$DOTFILES/scripts/install-pacman-sync-hook.sh"
ln -sf "$DOTFILES/scripts/dotfiles-sync.sh" "$HOME/.local/bin/dotfiles-sync"
echo "  -> ~/.local/bin/dotfiles-sync"
if [ -f "$DOTFILES/pacman/99-dotfiles-sync.hook.in" ]; then
    if command -v sudo >/dev/null 2>&1 && sudo -n true 2>/dev/null; then
        "$DOTFILES/scripts/install-pacman-sync-hook.sh"
    else
        echo "  !! pacman hook not installed; run: $DOTFILES/scripts/install-pacman-sync-hook.sh"
    fi
fi

# Clipboard-image paster (bound to Super+Shift+V in custom.conf). Needs wtype.
cp "$DOTFILES/hypr/clip-image-paste.sh" "$HOME/.local/bin/clip-image-paste.sh"
chmod +x "$HOME/.local/bin/clip-image-paste.sh"
echo "  -> ~/.local/bin/clip-image-paste.sh"

# Kitty smart paste: text paste normally, image paste as a typed file path.
cp "$DOTFILES/kitty/smart-paste.sh" "$HOME/.local/bin/kitty-smart-paste.sh"
chmod +x "$HOME/.local/bin/kitty-smart-paste.sh"
echo "  -> ~/.local/bin/kitty-smart-paste.sh"

# Area screenshot to image clipboard (bound to Super+S).
cp "$DOTFILES/hypr/screenshot-area-clipboard.sh" "$HOME/.local/bin/screenshot-area-clipboard.sh"
chmod +x "$HOME/.local/bin/screenshot-area-clipboard.sh"
echo "  -> ~/.local/bin/screenshot-area-clipboard.sh"

# Active window screenshot to image clipboard (bound to PrintScreen).
cp "$DOTFILES/hypr/screenshot-active-clipboard.sh" "$HOME/.local/bin/screenshot-active-clipboard.sh"
chmod +x "$HOME/.local/bin/screenshot-active-clipboard.sh"
echo "  -> ~/.local/bin/screenshot-active-clipboard.sh"

# Monitor layout (normally regenerated by nwg-displays; restore our saved one)
if [ -f "$DOTFILES/hypr/monitors.conf" ]; then
    cp "$DOTFILES/hypr/monitors.conf" "$HOME/.config/hypr/monitors.conf"
    echo "  -> hypr/monitors.conf"
fi

# VSCode settings (extensions are restored separately — see packages/ workflow)
if [ -d "$HOME/.config/Code/User" ]; then
    cp "$DOTFILES/vscode/settings.json" "$HOME/.config/Code/User/settings.json"
    echo "  -> Code/User/settings.json"
fi

# Kitty custom config + custom tab bar drawer
cp "$DOTFILES/kitty/custom.conf" "$HOME/.config/kitty/custom.conf"
echo "  -> kitty/custom.conf"
cp "$DOTFILES/kitty/tab_bar.py" "$HOME/.config/kitty/tab_bar.py"
echo "  -> kitty/tab_bar.py"

# Fish conf.d (only our 50-martin-* files, don't clobber ml4w's)
for f in "$DOTFILES"/fish/conf.d/*.fish; do
    cp "$f" "$HOME/.config/fish/conf.d/"
    echo "  -> fish/conf.d/$(basename "$f")"
done

# Sidepad: patched for multi-monitor absolute positioning
cp "$DOTFILES/sidepad/sidepad" "$HOME/.config/sidepad/sidepad"
chmod +x "$HOME/.config/sidepad/sidepad"
echo "  -> sidepad/sidepad"

# Dev Stacks: owned Quickshell instance for the Waybar infra pulse
QS_CONTAINERS="$HOME/.config/quickshell-containers"
mkdir -p "$QS_CONTAINERS"
if command -v rsync >/dev/null 2>&1; then
    rsync -a --delete "$DOTFILES/containers/" "$QS_CONTAINERS/"
else
    cp -R "$DOTFILES/containers/." "$QS_CONTAINERS/"
fi
chmod +x "$QS_CONTAINERS/scripts/"*.sh
echo "  -> quickshell-containers/"

# Project picker: owned Quickshell instance for current-project selection.
QS_PROJECTS="$HOME/.config/quickshell-projects"
mkdir -p "$QS_PROJECTS"
if command -v rsync >/dev/null 2>&1; then
    rsync -a --delete "$DOTFILES/dev/quickshell/" "$QS_PROJECTS/"
else
    cp -R "$DOTFILES/dev/quickshell/." "$QS_PROJECTS/"
fi
echo "  -> quickshell-projects/"

# Waybar: patch workspace and Project Hub modules.
WAYBAR_MODULES="$HOME/.config/waybar/modules.json"
if [ -f "$WAYBAR_MODULES" ]; then
    python3 - "$WAYBAR_MODULES" "$DOTFILES/waybar/modules-workspace-override.jsonc" "$DOTFILES/dev/waybar/module.jsonc" "$HOME/.config/waybar/themes" "$HOME/.config/waybar" <<'PY'
import json
import shutil
import sys
from pathlib import Path

modules_path = Path(sys.argv[1])
workspace_override_path = Path(sys.argv[2])
project_module_path = Path(sys.argv[3])
themes_dir = Path(sys.argv[4])
waybar_dir = Path(sys.argv[5])


def strip_jsonc(text):
    out = []
    i = 0
    in_string = False
    escaped = False
    while i < len(text):
        ch = text[i]
        nxt = text[i + 1] if i + 1 < len(text) else ""

        if in_string:
            out.append(ch)
            if escaped:
                escaped = False
            elif ch == "\\":
                escaped = True
            elif ch == '"':
                in_string = False
            i += 1
            continue

        if ch == '"':
            in_string = True
            out.append(ch)
            i += 1
            continue
        if ch == "/" and nxt == "/":
            i += 2
            while i < len(text) and text[i] not in "\r\n":
                i += 1
            continue
        if ch == "/" and nxt == "*":
            i += 2
            while i + 1 < len(text) and not (text[i] == "*" and text[i + 1] == "/"):
                i += 1
            i += 2
            continue

        out.append(ch)
        i += 1

    clean = "".join(out)
    import re
    return re.sub(r",\s*([}\]])", r"\1", clean)


def load_jsonc(path):
    return json.loads(strip_jsonc(path.read_text()))


def backup_once(path):
    backup = Path(str(path) + ".bak")
    if not backup.exists():
        shutil.copy2(path, backup)


def write_json(path, data):
    path.write_text(json.dumps(data, indent=2) + "\n")


def array_bounds(text, key):
    key_pos = text.find(f'"{key}"')
    if key_pos < 0:
        return None
    start = text.find("[", key_pos)
    if start < 0:
        return None

    in_string = False
    escaped = False
    depth = 0
    for i in range(start, len(text)):
        ch = text[i]
        if in_string:
            if escaped:
                escaped = False
            elif ch == "\\":
                escaped = True
            elif ch == '"':
                in_string = False
            continue

        if ch == '"':
            in_string = True
        elif ch == "[":
            depth += 1
        elif ch == "]":
            depth -= 1
            if depth == 0:
                return start, i
    return None


def module_name(line):
    return line.strip().rstrip(",").strip().strip('"')


def array_lines(text, key):
    bounds = array_bounds(text, key)
    if not bounds:
        return None

    start, end = bounds
    return start, end, text[start + 1 : end].splitlines(keepends=True)


def item_indent(lines):
    item_indent = "        "
    for line in lines:
        stripped = line.lstrip()
        if stripped.startswith('"'):
            item_indent = line[: len(line) - len(stripped)]
            break
    return item_indent


def rewrite_array(text, key, transform):
    details = array_lines(text, key)
    if not details:
        return text
    start, end, lines = details
    updated_lines = transform(lines)
    return text[: start + 1] + "".join(updated_lines) + text[end:]


def array_has(text, key, wanted):
    details = array_lines(text, key)
    if not details:
        return False
    _, _, lines = details
    return any(module_name(line) == wanted for line in lines)


def remove_modules(text, key, names):
    return rewrite_array(text, key, lambda lines: [line for line in lines if module_name(line) not in names])


def insert_project_island(text):
    managed_modules = {
        "custom/containers",
        "custom/current-project",
        "custom/project-label",
        "custom/project-action",
    }

    for key in ("modules-left", "modules-center", "modules-right"):
        text = remove_modules(text, key, managed_modules)

    # The island lives on the left with the clock. If a theme had the clock on
    # the right, move it left once and keep subsequent deploys stable.
    for key in ("modules-center", "modules-right"):
        text = remove_modules(text, key, {"clock"})

    def transform_left(lines):
        indent = item_indent(lines)
        names = [module_name(line) for line in lines]
        if "clock" not in names:
            clock_entry = f'{indent}"clock",\n'
            insert_at = 0
            for index, name in enumerate(names):
                if name in {"custom/appmenu", "custom/appmenuicon"}:
                    insert_at = index + 1
                    break
            lines = [*lines]
            lines.insert(insert_at, clock_entry)

        label_entry = f'{indent}"custom/project-label",\n'
        action_entry = f'{indent}"custom/project-action",\n'
        for index, line in enumerate(lines):
            if module_name(line) == "clock":
                lines.insert(index + 1, label_entry)
                lines.insert(index + 2, action_entry)
                return lines

        lines.append(label_entry)
        lines.append(action_entry)
        return lines

    return rewrite_array(text, "modules-left", transform_left)


def remove_marked_block(text, start, end):
    if start not in text or end not in text:
        return text
    before, rest = text.split(start, 1)
    _, after = rest.split(end, 1)
    return before.rstrip() + "\n\n" + after.lstrip()



def patch_style(path):
    if not path.exists():
        return False

    old_start = "/* dotfiles current-project start */"
    old_end = "/* dotfiles current-project end */"
    start = "/* dotfiles project-hub start */"
    end = "/* dotfiles project-hub end */"
    block = f"""{start}
#custom-project-action.running {{
    color: #8bd99c;
}}

#custom-project-action.working {{
    color: #e0bbde;
}}

#custom-project-action.alert {{
    color: #ffb4ab;
}}

#custom-project-action.stopped {{
    color: #c5c6d0;
}}
{end}
"""

    original = path.read_text()
    updated = remove_marked_block(original, old_start, old_end)
    updated = remove_marked_block(updated, start, end)
    updated = updated.rstrip() + "\n\n" + block

    if updated == original:
        return False

    backup_once(path)
    path.write_text(updated)
    return True


modules = load_jsonc(modules_path)
workspace_override = load_jsonc(workspace_override_path)
project_module = load_jsonc(project_module_path)

backup_once(modules_path)
modules["hyprland/workspaces"] = workspace_override["hyprland/workspaces"]
modules.pop("custom/current-project", None)
modules.pop("custom/containers", None)
modules.update(project_module)
write_json(modules_path, modules)

touched_themes = []
for config_path in sorted(themes_dir.glob("*/config")):
    data = load_jsonc(config_path)
    includes = data.get("include", [])
    if isinstance(includes, str):
        includes = [includes]
    if "~/.config/waybar/modules.json" not in includes:
        continue

    modules_left = data.get("modules-left")
    if not isinstance(modules_left, list):
        continue

    original = config_path.read_text()
    updated = insert_project_island(original)
    if updated == original:
        continue

    backup_once(config_path)
    config_path.write_text(updated)
    touched_themes.append(config_path.name if config_path.parent == themes_dir else config_path.parent.name)

styled = []
style_paths = {waybar_dir / "style.css", *themes_dir.glob("**/style.css")}
for style_path in sorted(style_paths):
    if patch_style(style_path):
        styled.append(str(style_path.relative_to(waybar_dir)))

print("themes=" + ",".join(touched_themes))
print("styles=" + ",".join(styled))
PY
    echo "  -> waybar/modules.json (workspace + Project Hub patched, one-time backup at modules.json.bak)"
    echo "  -> waybar/themes/*/config (Project Hub island inserted where modules.json is included)"
fi

echo ""
echo "Done. To apply changes:"
echo "  - Desktop shell: Super+Shift+R to reload Hyprland + Waybar"
echo "  - Hyprland only: Super+Ctrl+R to reload config (or hyprctl reload)"
echo "  - Kitty:    kill -SIGUSR1 \$(pgrep kitty)  (live reload, no restart needed)"
echo "  - VSCode:   restore extensions with:  cat vscode/extensions.txt | xargs -L1 code --install-extension"
