#!/usr/bin/env bash
set -euo pipefail

DOTFILES="$(cd "$(dirname "$0")" && pwd)"

echo "Deploying from $DOTFILES ..."

# Hyprland custom config
cp "$DOTFILES/hypr/custom.conf" "$HOME/.config/hypr/conf/custom.conf"
echo "  -> hypr/conf/custom.conf"

# Hyprland plugin auto-rebuild script (run via exec-once in custom.conf)
mkdir -p "$HOME/.local/bin"
cp "$DOTFILES/hypr/hyprpm-autoupdate.sh" "$HOME/.local/bin/hyprpm-autoupdate.sh"
chmod +x "$HOME/.local/bin/hyprpm-autoupdate.sh"
echo "  -> ~/.local/bin/hyprpm-autoupdate.sh"
cp "$DOTFILES/hypr/reload-desktop.sh" "$HOME/.local/bin/reload-desktop.sh"
chmod +x "$HOME/.local/bin/reload-desktop.sh"
echo "  -> ~/.local/bin/reload-desktop.sh"

# Coolify staging deploy notifications (systemd user timer -> notify-send)
cp "$DOTFILES/scripts/coolify-staging-notify.sh" "$HOME/.local/bin/coolify-staging-notify.sh"
chmod +x "$HOME/.local/bin/coolify-staging-notify.sh"
mkdir -p "$HOME/.config/systemd/user"
cp "$DOTFILES/systemd/coolify-staging-notify.service" \
   "$DOTFILES/systemd/coolify-staging-notify.timer" \
   "$HOME/.config/systemd/user/"
systemctl --user daemon-reload
systemctl --user enable --now coolify-staging-notify.timer >/dev/null 2>&1 || true
echo "  -> coolify-staging-notify (script + user timer enabled)"

# Project Hub: current-project workflow and infra controls.
mkdir -p "$HOME/.config/dev" "$HOME/.local/bin"
cp "$DOTFILES/project-hub/projects.json" "$HOME/.config/dev/projects.json"
echo "  -> project-hub/projects.json"
if [ ! -s "$HOME/.config/dev/current-project" ]; then
    python3 - "$HOME/.config/dev/projects.json" "$HOME/.config/dev/current-project" <<'PY'
import json
import sys
from pathlib import Path

projects_path = Path(sys.argv[1])
current_path = Path(sys.argv[2])
projects = json.loads(projects_path.read_text())
if projects:
    current_path.write_text(str(projects[0]["path"]) + "\n")
PY
    echo "  -> dev/current-project"
fi
cp "$DOTFILES/project-hub/scripts/dev-project" "$HOME/.local/bin/dev-project"
chmod +x "$HOME/.local/bin/dev-project"
echo "  -> ~/.local/bin/dev-project"
"$HOME/.local/bin/dev-project" scan --quiet
echo "  -> project-hub scan"
rm -f "$HOME/.config/dev/project-shortcuts.zsh" "$HOME/.config/dev/project-shortcuts.fish"
echo "  -> removed legacy project shortcut files"
cp "$DOTFILES/project-hub/scripts/project-hub-watch" "$HOME/.local/bin/project-hub-watch"
chmod +x "$HOME/.local/bin/project-hub-watch"
echo "  -> ~/.local/bin/project-hub-watch"

# Dotfiles sync helper + pacman hook.
chmod +x "$DOTFILES/scripts/dotfiles-sync.sh" \
    "$DOTFILES/scripts/dotfiles-pacman-hook.sh" \
    "$DOTFILES/scripts/install-pacman-sync-hook.sh" \
    "$DOTFILES/scripts/disable-hyprland-split-workspaces.sh" \
    "$DOTFILES/scripts/patch-waybar-project-hub.py"
ln -sf "$DOTFILES/scripts/dotfiles-sync.sh" "$HOME/.local/bin/dotfiles-sync"
echo "  -> ~/.local/bin/dotfiles-sync"
ln -sf "$DOTFILES/scripts/dotfiles-pacman-hook.sh" "$HOME/.local/bin/dotfiles-pacman-hook"
echo "  -> ~/.local/bin/dotfiles-pacman-hook"
ln -sf "$DOTFILES/scripts/disable-hyprland-split-workspaces.sh" "$HOME/.local/bin/disable-hyprland-split-workspaces"
echo "  -> ~/.local/bin/disable-hyprland-split-workspaces"
if [ -f "$DOTFILES/pacman/99-dotfiles-sync.hook.in" ]; then
    if command -v sudo >/dev/null 2>&1 && sudo -n true 2>/dev/null; then
        "$DOTFILES/scripts/install-pacman-sync-hook.sh"
    else
        echo "  !! pacman hook not installed; run: $DOTFILES/scripts/install-pacman-sync-hook.sh"
    fi
fi

# Smart clipboard paste (bound to Ctrl+V in kitty/custom.conf): image -> typed
# file path, text -> kitty bracketed paste. Needs wtype + kitty remote control.
cp "$DOTFILES/kitty/clip-smart-paste.sh" "$HOME/.local/bin/clip-smart-paste.sh"
chmod +x "$HOME/.local/bin/clip-smart-paste.sh"
echo "  -> ~/.local/bin/clip-smart-paste.sh"

# Area screenshot to image clipboard (bound to Super+S).
cp "$DOTFILES/hypr/screenshot-area-clipboard.sh" "$HOME/.local/bin/screenshot-area-clipboard.sh"
chmod +x "$HOME/.local/bin/screenshot-area-clipboard.sh"
echo "  -> ~/.local/bin/screenshot-area-clipboard.sh"

# Active window screenshot to image clipboard (bound to PrintScreen).
cp "$DOTFILES/hypr/screenshot-active-clipboard.sh" "$HOME/.local/bin/screenshot-active-clipboard.sh"
chmod +x "$HOME/.local/bin/screenshot-active-clipboard.sh"
echo "  -> ~/.local/bin/screenshot-active-clipboard.sh"

# Monitor layout (normally regenerated by nwg-displays; restore our saved one)
if [ -f "$DOTFILES/hypr/monitors.conf" ]; then
    cp "$DOTFILES/hypr/monitors.conf" "$HOME/.config/hypr/monitors.conf"
    echo "  -> hypr/monitors.conf"
fi

# VSCode settings (extensions are restored separately — see packages/ workflow)
if [ -d "$HOME/.config/Code/User" ]; then
    cp "$DOTFILES/vscode/settings.json" "$HOME/.config/Code/User/settings.json"
    echo "  -> Code/User/settings.json"
fi

# Kitty custom config + custom tab bar drawer
cp "$DOTFILES/kitty/custom.conf" "$HOME/.config/kitty/custom.conf"
echo "  -> kitty/custom.conf"
cp "$DOTFILES/kitty/tab_bar.py" "$HOME/.config/kitty/tab_bar.py"
echo "  -> kitty/tab_bar.py"

# Remove legacy Martin-owned shell files from the previous shell setup.
rm -f "$HOME/.config/fish/conf.d/50-martin-aliases.fish" \
    "$HOME/.config/fish/conf.d/50-martin-env.fish"
echo "  -> removed legacy fish conf.d files"

# Zsh conf.d: personal additions (50-martin etc.)
for f in "$DOTFILES"/zsh/conf.d/*; do
    cp "$f" "$HOME/.config/zshrc/$(basename "$f")"
    echo "  -> zshrc/$(basename "$f")"
done

# Zsh custom: overrides that replace ML4W defaults (e.g. fix broken OMZ path)
mkdir -p "$HOME/.config/zshrc/custom"
for f in "$DOTFILES"/zsh/custom/*; do
    cp "$f" "$HOME/.config/zshrc/custom/$(basename "$f")"
    echo "  -> zshrc/custom/$(basename "$f")"
done

# Sidepad: patched for multi-monitor absolute positioning
cp "$DOTFILES/sidepad/sidepad" "$HOME/.config/sidepad/sidepad"
chmod +x "$HOME/.config/sidepad/sidepad"
echo "  -> sidepad/sidepad"

# Project Hub infra backend: owned Quickshell instance for compatibility.
QS_CONTAINERS="$HOME/.config/quickshell-containers"
mkdir -p "$QS_CONTAINERS"
if command -v rsync >/dev/null 2>&1; then
    rsync -a --delete "$DOTFILES/project-hub/containers/" "$QS_CONTAINERS/"
else
    cp -R "$DOTFILES/project-hub/containers/." "$QS_CONTAINERS/"
fi
chmod +x "$QS_CONTAINERS/scripts/"*.sh
echo "  -> quickshell-containers/"

# Project Hub picker: owned Quickshell instance for current-project selection.
QS_PROJECTS="$HOME/.config/quickshell-projects"
mkdir -p "$QS_PROJECTS"
if command -v rsync >/dev/null 2>&1; then
    rsync -a --delete "$DOTFILES/project-hub/quickshell/" "$QS_PROJECTS/"
else
    cp -R "$DOTFILES/project-hub/quickshell/." "$QS_PROJECTS/"
fi
echo "  -> quickshell-projects/"

# Waybar: patch workspace and Project Hub modules.
WAYBAR_MODULES="$HOME/.config/waybar/modules.json"
if [ -f "$WAYBAR_MODULES" ]; then
    python3 "$DOTFILES/scripts/patch-waybar-project-hub.py" \
        "$WAYBAR_MODULES" \
        "$DOTFILES/waybar/modules-workspace-override.jsonc" \
        "$DOTFILES/project-hub/waybar/module.jsonc" \
        "$HOME/.config/waybar/themes" \
        "$HOME/.config/waybar"
    echo "  -> waybar/modules.json (workspace + Project Hub patched, one-time backup at modules.json.bak)"
    echo "  -> waybar/themes/*/config (Project Hub island inserted where modules.json is included)"
fi

echo ""
echo "Done. To apply changes:"
echo "  - Desktop shell: Super+Shift+R to reload Hyprland + Waybar"
echo "  - Hyprland only: Super+Ctrl+R to reload config (or hyprctl reload)"
echo "  - Kitty:    kill -SIGUSR1 \$(pgrep kitty)  (live reload, no restart needed)"
echo "  - VSCode:   restore extensions with:  cat vscode/extensions.txt | xargs -L1 code --install-extension"
