#!/usr/bin/env bash
set -euo pipefail

DOTFILES="$(cd "$(dirname "$0")" && pwd)"

echo "Deploying from $DOTFILES ..."

# Hyprland custom config
cp "$DOTFILES/hypr/custom.conf" "$HOME/.config/hypr/conf/custom.conf"
echo "  -> hypr/conf/custom.conf"

# Hyprland plugin auto-rebuild script (run via exec-once in custom.conf)
mkdir -p "$HOME/.local/bin"
cp "$DOTFILES/hypr/hyprpm-autoupdate.sh" "$HOME/.local/bin/hyprpm-autoupdate.sh"
chmod +x "$HOME/.local/bin/hyprpm-autoupdate.sh"
echo "  -> ~/.local/bin/hyprpm-autoupdate.sh"

# Dotfiles sync helper + pacman hook.
chmod +x "$DOTFILES/scripts/dotfiles-sync.sh" \
    "$DOTFILES/scripts/dotfiles-pacman-hook.sh" \
    "$DOTFILES/scripts/install-pacman-sync-hook.sh"
ln -sf "$DOTFILES/scripts/dotfiles-sync.sh" "$HOME/.local/bin/dotfiles-sync"
echo "  -> ~/.local/bin/dotfiles-sync"
if [ -f "$DOTFILES/pacman/99-dotfiles-sync.hook.in" ]; then
    if command -v sudo >/dev/null 2>&1 && sudo -n true 2>/dev/null; then
        "$DOTFILES/scripts/install-pacman-sync-hook.sh"
    else
        echo "  !! pacman hook not installed; run: $DOTFILES/scripts/install-pacman-sync-hook.sh"
    fi
fi

# Clipboard-image paster (bound to Super+Shift+V in custom.conf). Needs wtype.
cp "$DOTFILES/hypr/clip-image-paste.sh" "$HOME/.local/bin/clip-image-paste.sh"
chmod +x "$HOME/.local/bin/clip-image-paste.sh"
echo "  -> ~/.local/bin/clip-image-paste.sh"

# Kitty smart paste: text paste normally, image paste as a typed file path.
cp "$DOTFILES/kitty/smart-paste.sh" "$HOME/.local/bin/kitty-smart-paste.sh"
chmod +x "$HOME/.local/bin/kitty-smart-paste.sh"
echo "  -> ~/.local/bin/kitty-smart-paste.sh"

# Area screenshot to image clipboard (bound to Super+S).
cp "$DOTFILES/hypr/screenshot-area-clipboard.sh" "$HOME/.local/bin/screenshot-area-clipboard.sh"
chmod +x "$HOME/.local/bin/screenshot-area-clipboard.sh"
echo "  -> ~/.local/bin/screenshot-area-clipboard.sh"

# Active window screenshot to image clipboard (bound to PrintScreen).
cp "$DOTFILES/hypr/screenshot-active-clipboard.sh" "$HOME/.local/bin/screenshot-active-clipboard.sh"
chmod +x "$HOME/.local/bin/screenshot-active-clipboard.sh"
echo "  -> ~/.local/bin/screenshot-active-clipboard.sh"

# Monitor layout (normally regenerated by nwg-displays; restore our saved one)
if [ -f "$DOTFILES/hypr/monitors.conf" ]; then
    cp "$DOTFILES/hypr/monitors.conf" "$HOME/.config/hypr/monitors.conf"
    echo "  -> hypr/monitors.conf"
fi

# VSCode settings (extensions are restored separately — see packages/ workflow)
if [ -d "$HOME/.config/Code/User" ]; then
    cp "$DOTFILES/vscode/settings.json" "$HOME/.config/Code/User/settings.json"
    echo "  -> Code/User/settings.json"
fi

# Kitty custom config + custom tab bar drawer
cp "$DOTFILES/kitty/custom.conf" "$HOME/.config/kitty/custom.conf"
echo "  -> kitty/custom.conf"
cp "$DOTFILES/kitty/tab_bar.py" "$HOME/.config/kitty/tab_bar.py"
echo "  -> kitty/tab_bar.py"

# Fish conf.d (only our 50-martin-* files, don't clobber ml4w's)
for f in "$DOTFILES"/fish/conf.d/*.fish; do
    cp "$f" "$HOME/.config/fish/conf.d/"
    echo "  -> fish/conf.d/$(basename "$f")"
done

# Sidepad: patched for multi-monitor absolute positioning
cp "$DOTFILES/sidepad/sidepad" "$HOME/.config/sidepad/sidepad"
chmod +x "$HOME/.config/sidepad/sidepad"
echo "  -> sidepad/sidepad"

# Dev Stacks: owned Quickshell instance for the Waybar infra pulse
QS_CONTAINERS="$HOME/.config/quickshell-containers"
mkdir -p "$QS_CONTAINERS"
if command -v rsync >/dev/null 2>&1; then
    rsync -a --delete "$DOTFILES/containers/" "$QS_CONTAINERS/"
else
    cp -R "$DOTFILES/containers/." "$QS_CONTAINERS/"
fi
chmod +x "$QS_CONTAINERS/scripts/"*.sh
echo "  -> quickshell-containers/"

# Waybar: patch workspace module and Dev Stacks module in modules.json
WAYBAR_MODULES="$HOME/.config/waybar/modules.json"
if [ -f "$WAYBAR_MODULES" ]; then
    python3 - "$WAYBAR_MODULES" "$DOTFILES/waybar/modules-workspace-override.jsonc" "$DOTFILES/containers/waybar/module.jsonc" "$HOME/.config/waybar/themes" <<'PY'
import json
import shutil
import sys
from pathlib import Path

modules_path = Path(sys.argv[1])
workspace_override_path = Path(sys.argv[2])
containers_module_path = Path(sys.argv[3])
themes_dir = Path(sys.argv[4])


def strip_jsonc(text):
    out = []
    i = 0
    in_string = False
    escaped = False
    while i < len(text):
        ch = text[i]
        nxt = text[i + 1] if i + 1 < len(text) else ""

        if in_string:
            out.append(ch)
            if escaped:
                escaped = False
            elif ch == "\\":
                escaped = True
            elif ch == '"':
                in_string = False
            i += 1
            continue

        if ch == '"':
            in_string = True
            out.append(ch)
            i += 1
            continue
        if ch == "/" and nxt == "/":
            i += 2
            while i < len(text) and text[i] not in "\r\n":
                i += 1
            continue
        if ch == "/" and nxt == "*":
            i += 2
            while i + 1 < len(text) and not (text[i] == "*" and text[i + 1] == "/"):
                i += 1
            i += 2
            continue

        out.append(ch)
        i += 1

    clean = "".join(out)
    import re
    return re.sub(r",\s*([}\]])", r"\1", clean)


def load_jsonc(path):
    return json.loads(strip_jsonc(path.read_text()))


def backup_once(path):
    backup = Path(str(path) + ".bak")
    if not backup.exists():
        shutil.copy2(path, backup)


def write_json(path, data):
    path.write_text(json.dumps(data, indent=2) + "\n")


def array_bounds(text, key):
    key_pos = text.find(f'"{key}"')
    if key_pos < 0:
        return None
    start = text.find("[", key_pos)
    if start < 0:
        return None

    in_string = False
    escaped = False
    depth = 0
    for i in range(start, len(text)):
        ch = text[i]
        if in_string:
            if escaped:
                escaped = False
            elif ch == "\\":
                escaped = True
            elif ch == '"':
                in_string = False
            continue

        if ch == '"':
            in_string = True
        elif ch == "[":
            depth += 1
        elif ch == "]":
            depth -= 1
            if depth == 0:
                return start, i
    return None


def insert_theme_module(text):
    bounds = array_bounds(text, "modules-right")
    if not bounds:
        return text

    start, end = bounds
    before = text[: start + 1]
    array_body = text[start + 1 : end]
    after = text[end:]
    lines = array_body.splitlines(keepends=True)

    item_indent = "        "
    for line in lines:
        stripped = line.lstrip()
        if stripped.startswith('"'):
            item_indent = line[: len(line) - len(stripped)]
            break

    def is_containers(line):
        return line.strip().rstrip(",").strip().strip('"') == "custom/containers"

    # Drop any existing entry first so re-running re-homes it canonically
    # (idempotent: a no-op once it's already in the right spot).
    lines = [line for line in lines if not is_containers(line)]

    entry = f'{item_indent}"custom/containers",\n'

    # Preferred home: immediately to the right of the updates module
    # (left edge of the right-hand island).
    for index, line in enumerate(lines):
        if '"custom/updates"' in line:
            lines.insert(index + 1, entry)
            return before + "".join(lines) + after

    # Fallbacks for themes without an updates module.
    for index, line in enumerate(lines):
        if '"custom/notification"' in line:
            lines.insert(index, entry)
            return before + "".join(lines) + after

    for index, line in enumerate(lines):
        if '"tray"' in line:
            lines.insert(index + 1, entry)
            return before + "".join(lines) + after

    lines.append(entry)
    return before + "".join(lines) + after


modules = load_jsonc(modules_path)
workspace_override = load_jsonc(workspace_override_path)
containers_module = load_jsonc(containers_module_path)

backup_once(modules_path)
modules["hyprland/workspaces"] = workspace_override["hyprland/workspaces"]
modules.update(containers_module)
write_json(modules_path, modules)

touched_themes = []
for config_path in sorted(themes_dir.glob("*/config")):
    data = load_jsonc(config_path)
    includes = data.get("include", [])
    if isinstance(includes, str):
        includes = [includes]
    if "~/.config/waybar/modules.json" not in includes:
        continue

    modules_right = data.get("modules-right")
    if not isinstance(modules_right, list):
        continue

    original = config_path.read_text()
    updated = insert_theme_module(original)
    if updated == original:
        continue

    backup_once(config_path)
    config_path.write_text(updated)
    touched_themes.append(config_path.name if config_path.parent == themes_dir else config_path.parent.name)

print("themes=" + ",".join(touched_themes))
PY
    echo "  -> waybar/modules.json (workspace + dev stacks patched, one-time backup at modules.json.bak)"
    echo "  -> waybar/themes/*/config (dev stacks inserted where modules.json is included)"
fi

echo ""
echo "Done. To apply changes:"
echo "  - Hyprland: Super+Ctrl+R to reload config (or hyprctl reload)"
echo "  - Waybar:   Super+Shift+B to reload (or killall waybar && ~/.config/waybar/launch.sh &)"
echo "  - Kitty:    kill -SIGUSR1 \$(pgrep kitty)  (live reload, no restart needed)"
echo "  - VSCode:   restore extensions with:  cat vscode/extensions.txt | xargs -L1 code --install-extension"
