#!/usr/bin/env bash
# snapshot.sh — pull machine state INTO the repo (the reverse of deploy.sh).
#
# deploy.sh pushes repo -> system. This captures the things that drift over time
# (installed packages, VSCode extensions, monitor layout) system -> repo so they
# can be committed. Run it before committing when you've installed/changed stuff.
set -euo pipefail

DOTFILES="$(cd "$(dirname "$0")" && pwd)"
cd "$DOTFILES"

echo "Snapshotting machine state into $DOTFILES ..."

# Explicitly-installed packages (includes AUR) and the foreign/AUR subset
mkdir -p packages
pacman -Qqe > packages/pacman-explicit.txt
pacman -Qqm > packages/aur.txt
echo "  -> packages/pacman-explicit.txt ($(wc -l < packages/pacman-explicit.txt)), packages/aur.txt ($(wc -l < packages/aur.txt))"

# VSCode: settings + the extension list (skip mcp.json — may hold secrets)
if command -v code >/dev/null 2>&1; then
    mkdir -p vscode
    cp ~/.config/Code/User/settings.json vscode/settings.json
    code --list-extensions > vscode/extensions.txt
    echo "  -> vscode/settings.json, vscode/extensions.txt ($(wc -l < vscode/extensions.txt) extensions)"
fi

# Monitor layout (generated by nwg-displays; lives in the ML4W symlink dir)
if [ -f ~/.config/hypr/monitors.conf ]; then
    cp ~/.config/hypr/monitors.conf hypr/monitors.conf
    echo "  -> hypr/monitors.conf"
fi

# Claude Code: settings, hooks, statusline, global CLAUDE.md, skills
mkdir -p claude/hooks claude/skills/execution-plan
cp ~/.claude/settings.json       claude/settings.json
cp ~/.claude/settings.local.json claude/settings.local.json
cp ~/.claude/CLAUDE.md           claude/CLAUDE.md
cp ~/.claude/statusline.sh       claude/statusline.sh
cp ~/.claude/hooks/bash-guard.py  claude/hooks/bash-guard.py
cp ~/.claude/hooks/auto-format.sh claude/hooks/auto-format.sh
cp ~/.claude/skills/execution-plan/SKILL.md claude/skills/execution-plan/SKILL.md
echo "  -> claude/ (settings, hooks, statusline, CLAUDE.md, skills)"

echo ""
echo "Done. Review with 'git -C $DOTFILES diff' and commit."
